services:
  langflow:
    image: langflowai/langflow:latest  # 或者在 https://hub.docker.com/r/langflowai/langflow 选择特定版本
    pull_policy: always               # 'latest' 版本建议设为 'always'，确保拉取最新镜像
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/langflow
      # 配置存储目录，包括日志、文件存储、监控数据和密钥
      - LANGFLOW_CONFIG_DIR=/app/langflow
    volumes:
      - /home/qystart/docker/langflow/langflow:/app/langflow
